name: he_radiomics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - shap
    - statsmodels
    - scipy
